const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Product = require('../models/Product');

dotenv.config();

const sizesMen = ["S", "M", "L", "XL", "XXL"];
const sizesWomen = ["XS", "S", "M", "L", "XL"];
const sizesKids = ["2-3Y", "3-4Y", "5-6Y", "7-8Y", "9-10Y"];
const sizesAccessories = [];

const products = [
  // ACCESSORIES (10)
  {
    name: 'Black Casual Cap',
    image: '/images/accessories-black-cap.png',
    description: 'Classic black cap with adjustable strap for a perfect fit.',
    brand: 'UrbanGear',
    category: 'Accessories',
    price: 15.99,
    sizes: sizesAccessories,
    countInStock: 50,
  },
  {
    name: 'Leather Men\'s Wallet',
    image: '/images/accessories-men-wallet.png',
    description: 'Premium leather wallet for men with multiple card slots.',
    brand: 'LuxeLeather',
    category: 'Accessories',
    price: 35.00,
    sizes: sizesAccessories,
    countInStock: 30,
  },
  {
    name: 'Pack of 3 Men\'s Ankle Socks',
    image: '/images/accessories-pack-of-3-men-ankle-length-socks.png',
    description: 'Comfortable pack of 3 ankle-length socks for daily wear.',
    brand: 'SoftStep',
    category: 'Accessories',
    price: 12.99,
    sizes: sizesAccessories,
    countInStock: 100,
  },
  {
    name: 'Women\'s Classic Slim Belt',
    image: '/images/accessories-women-classic-slim-belt.png',
    description: 'Elegant slim belt for women, perfect for formal and casual wear.',
    brand: 'ChicStyle',
    category: 'Accessories',
    price: 19.99,
    sizes: sizesAccessories,
    countInStock: 40,
  },
  {
    name: 'Women\'s Crochet Bucket Hat',
    image: '/images/accessories-women-crochet-bucket-hat.png',
    description: 'Handcrafted crochet bucket hat for a trendy summer look.',
    brand: 'BohoVibe',
    category: 'Accessories',
    price: 24.50,
    sizes: sizesAccessories,
    countInStock: 25,
  },
  {
    name: 'Women\'s Striped Ankle Socks',
    image: '/images/accessories-women-striped-ankle-length-socks.png',
    description: 'Stylish striped ankle-length socks for women.',
    brand: 'ColorPop',
    category: 'Accessories',
    price: 8.99,
    sizes: sizesAccessories,
    countInStock: 80,
  },
  {
    name: 'Women\'s Zip Around Wallet',
    image: '/images/accessories-women-zip-around-wallet.png',
    description: 'Spacious zip-around wallet with elegant finish.',
    brand: 'LuxeLeather',
    category: 'Accessories',
    price: 45.00,
    sizes: sizesAccessories,
    countInStock: 20,
  },
  {
    name: 'Backpack with Adjustable Straps',
    image: '/images/accessories-backpack-with-adjustable-straps.png',
    description: 'Durable backpack with ergonomic design and adjustable straps.',
    brand: 'TravelEase',
    category: 'Accessories',
    price: 55.00,
    sizes: sizesAccessories,
    countInStock: 15,
  },
  {
    name: 'Men\'s Belt with Buckle Closure',
    image: '/images/accessories-men-belt-with-buckle-closure.png',
    description: 'Classic men\'s belt with a durable buckle closure.',
    brand: 'UrbanGear',
    category: 'Accessories',
    price: 22.99,
    sizes: sizesAccessories,
    countInStock: 45,
  },
  {
    name: 'Men\'s Stripes Socks',
    image: '/images/accessories-men-stripes-socks.png',
    description: 'Premium cotton socks with bold stripes.',
    brand: 'SoftStep',
    category: 'Accessories',
    price: 6.50,
    sizes: sizesAccessories,
    countInStock: 90,
  },

  // KIDS (16)
  {
    name: 'Block Print A-Line Dress',
    image: '/images/kids-block-print-A-line-dress.png',
    description: 'Beautiful block print A-line dress for girls.',
    brand: 'KidJoy',
    category: 'Kids',
    price: 28.50,
    sizes: sizesKids,
    countInStock: 20,
  },
  {
    name: 'Kids Performance Dress Set',
    image: '/images/kids-dress-set.png',
    description: 'Complete dress set for kids, comfortable and stylish.',
    brand: 'KidJoy',
    category: 'Kids',
    price: 45.00,
    sizes: sizesKids,
    countInStock: 15,
  },
  {
    name: 'Dungaree with Printed T-Shirt',
    image: '/images/kids-dungare-with-printed-tshirt.png',
    description: 'Cute dungaree set with a soft printed t-shirt.',
    brand: 'KidJoy',
    category: 'Kids',
    price: 32.99,
    sizes: sizesKids,
    countInStock: 25,
  },
  {
    name: 'Embroidered Gahrah Chole Set',
    image: '/images/kids-embroidered-gahahrachole-set.png',
    description: 'Traditional embroidered set for festive occasions.',
    brand: 'FestiveTots',
    category: 'Kids',
    price: 59.99,
    sizes: sizesKids,
    countInStock: 10,
  },
  {
    name: 'Embroidered Kids Shorts',
    image: '/images/kids-embroidered-short.png',
    description: 'Comfortable shorts with cute embroidery details.',
    brand: 'SoftStepKids',
    category: 'Kids',
    price: 18.00,
    sizes: sizesKids,
    countInStock: 35,
  },
  {
    name: 'Embroidered Square Neck Top',
    image: '/images/kids-embroidered-square-neck-denimtop.png',
    description: 'Stylish denim top with square neck and embroidery.',
    brand: 'KidJoy',
    category: 'Kids',
    price: 22.00,
    sizes: sizesKids,
    countInStock: 20,
  },
  {
    name: 'Kids Flare Dress',
    image: '/images/kids-flare-dress.png',
    description: 'Flowy flare dress for active girls.',
    brand: 'KidJoy',
    category: 'Kids',
    price: 26.50,
    sizes: sizesKids,
    countInStock: 30,
  },
  {
    name: 'Kids Floral Print Shirt',
    image: '/images/kids-floral-print-shirt.png',
    description: 'Vibrant floral print shirt for boys.',
    brand: 'KidJoy',
    category: 'Kids',
    price: 19.99,
    sizes: sizesKids,
    countInStock: 40,
  },
  {
    name: 'Cotton Dungaree Romper',
    image: '/images/kids-graphicprint-cotton-dungaree-romper.png',
    description: 'Soft cotton romper with graphic print.',
    brand: 'KidJoy',
    category: 'Kids',
    price: 29.50,
    sizes: sizesKids,
    countInStock: 25,
  },
  {
    name: 'One-Size Baby Romper Pack',
    image: '/images/kids-pack-of-2-onesizes.png',
    description: 'Pack of 2 comfortable one-size rompers for babies.',
    brand: 'SoftStepKids',
    category: 'Kids',
    price: 15.99,
    sizes: sizesKids,
    countInStock: 50,
  },
  {
    name: 'Round Neck T-Shirt Pack (3)',
    image: '/images/kids-packof-3-round-neck-tshirts.png',
    description: 'Essential pack of 3 round neck t-shirts.',
    brand: 'KidJoy',
    category: 'Kids',
    price: 24.99,
    sizes: sizesKids,
    countInStock: 60,
  },
  {
    name: 'Relaxed Printed T-Shirt Pack (3)',
    image: '/images/kids-packof3-relaxed-printed-tshirts.png',
    description: 'Pack of 3 relaxed fit printed t-shirts for daily wear.',
    brand: 'KidJoy',
    category: 'Kids',
    price: 27.50,
    sizes: sizesKids,
    countInStock: 45,
  },
  {
    name: 'Popcorn Dress Set',
    image: '/images/kids-popcorn-dress-set.png',
    description: 'Trendy dress set with popcorn texture fabric.',
    brand: 'KidJoy',
    category: 'Kids',
    price: 36.00,
    sizes: sizesKids,
    countInStock: 20,
  },
  {
    name: 'Kids Printed Dress',
    image: '/images/kids-printed-dress.png',
    description: 'Bright and colorful printed dress.',
    brand: 'KidJoy',
    category: 'Kids',
    price: 24.00,
    sizes: sizesKids,
    countInStock: 30,
  },
  {
    name: 'T-Shirts & Shorts Set',
    image: '/images/kids-printed2-tshirts-with-shorts.png',
    description: 'Coordinated set with 2 t-shirts and shorts.',
    brand: 'KidJoy',
    category: 'Kids',
    price: 38.99,
    sizes: sizesKids,
    countInStock: 15,
  },
  {
    name: 'Trackpant & Hoodie Set',
    image: '/images/kids-trackpant-and-hoodieset.png',
    description: 'Warm and comfortable hoodie set for winter.',
    brand: 'UrbanGearKids',
    category: 'Kids',
    price: 49.50,
    sizes: sizesKids,
    countInStock: 12,
  },

  // MEN (20)
  {
    name: 'Black Shaded Jeans',
    image: '/images/men-ankle-length-black-shaded-jeans.png',
    description: 'Modern black shaded jeans with an ankle-length fit.',
    brand: 'DenimCo',
    category: 'Men',
    price: 45.99,
    sizes: sizesMen,
    countInStock: 30,
  },
  {
    name: 'Classic Blue Jeans',
    image: '/images/men-blue-jeans.png',
    description: 'Evergreen classic blue denim jeans.',
    brand: 'DenimCo',
    category: 'Men',
    price: 42.00,
    sizes: sizesMen,
    countInStock: 40,
  },
  {
    name: 'Bootcut Denim Jeans',
    image: '/images/men-bootcut-jeans.png',
    description: 'Stylish bootcut jeans for a vintage look.',
    brand: 'DenimCo',
    category: 'Men',
    price: 48.50,
    sizes: sizesMen,
    countInStock: 25,
  },
  {
    name: 'Cargo Utility Shorts',
    image: '/images/men-cargo-short.png',
    description: 'Functional cargo shorts with multiple pockets.',
    brand: 'UrbanGear',
    category: 'Men',
    price: 29.99,
    sizes: sizesMen,
    countInStock: 35,
  },
  {
    name: 'Cotton Short Kurta',
    image: '/images/men-cotton-short-kurtha.png',
    description: 'Breathable cotton short kurta for a smart ethnic look.',
    brand: 'EthnicWear',
    category: 'Men',
    price: 35.00,
    sizes: sizesMen,
    countInStock: 20,
  },
  {
    name: 'Floral Print Men\'s Shirt',
    image: '/images/men-floral-print-shirt.png',
    description: 'Summer-ready floral print shirt for beach vacations.',
    brand: 'BeachVibe',
    category: 'Men',
    price: 26.99,
    sizes: sizesMen,
    countInStock: 50,
  },
  {
    name: 'Regular Fit Printed Shirt',
    image: '/images/men-printed-regular-fit-shirt.png',
    description: 'Classic regular fit shirt with a subtle print.',
    brand: 'UrbanGear',
    category: 'Men',
    price: 32.50,
    sizes: sizesMen,
    countInStock: 40,
  },
  {
    name: 'Printed Casual Shorts',
    image: '/images/men-printed-regular-fit-short.png',
    description: 'Relaxed fit printed shorts for comfort.',
    brand: 'UrbanGear',
    category: 'Men',
    price: 22.00,
    sizes: sizesMen,
    countInStock: 45,
  },
  {
    name: 'Silk Blend Kurta',
    image: '/images/men-printed-silk-blend-kurtha.png',
    description: 'Premium silk blend kurta for formal ethnic events.',
    brand: 'EthnicWear',
    category: 'Men',
    price: 75.00,
    sizes: sizesMen,
    countInStock: 15,
  },
  {
    name: 'Regular Fit Joggers',
    image: '/images/men-regular-fit-jogger.png',
    description: 'Comfortable cotton joggers with elastic waist.',
    brand: 'SportyLife',
    category: 'Men',
    price: 38.00,
    sizes: sizesMen,
    countInStock: 30,
  },
  {
    name: 'Regular Fit Polo T-Shirt',
    image: '/images/men-regular-fit-polo-tshirt.png',
    description: 'Classic polo t-shirt for a semi-formal look.',
    brand: 'UrbanGear',
    category: 'Men',
    price: 28.00,
    sizes: sizesMen,
    countInStock: 50,
  },
  {
    name: 'Spread Collar Shirt',
    image: '/images/men-regular-fit-shirt-with-spread-color.png',
    description: 'Formal shirt with a clean spread collar design.',
    brand: 'UrbanGear',
    category: 'Men',
    price: 39.99,
    sizes: sizesMen,
    countInStock: 25,
  },
  {
    name: 'Men\'s Regular Trackpant',
    image: '/images/men-regular-trackpant.png',
    description: 'Everyday trackpant for sports and lounging.',
    brand: 'SportyLife',
    category: 'Men',
    price: 25.50,
    sizes: sizesMen,
    countInStock: 60,
  },
  {
    name: 'Self-Design Sherwani Set',
    image: '/images/men-self-design-sherwani-set.png',
    description: 'Elegant self-design sherwani for wedding wear.',
    brand: 'FestiveWear',
    category: 'Men',
    price: 299.00,
    sizes: sizesMen,
    countInStock: 5,
  },
  {
    name: 'Embroidered Sherwani Set',
    image: '/images/men-sherwani-set.png',
    description: 'Richly embroidered sherwani set for grand events.',
    brand: 'FestiveWear',
    category: 'Men',
    price: 350.00,
    sizes: sizesMen,
    countInStock: 3,
  },
  {
    name: 'Sleeveless Gym T-Shirt',
    image: '/images/men-sleeveless-tshirt.png',
    description: 'Breathable sleeveless top for high-intensity workouts.',
    brand: 'SportyLife',
    category: 'Men',
    price: 18.99,
    sizes: sizesMen,
    countInStock: 50,
  },
  {
    name: 'Slim Fit Collar T-Shirt',
    image: '/images/men-slimfit-collar-t-shirt.png',
    description: 'Trendy slim fit t-shirt with a stylish collar.',
    brand: 'UrbanGear',
    category: 'Men',
    price: 24.50,
    sizes: sizesMen,
    countInStock: 45,
  },
  {
    name: 'Performance Sport Shorts',
    image: '/images/men-sports-short.png',
    description: 'Lightweight shorts designed for athletics.',
    brand: 'SportyLife',
    category: 'Men',
    price: 21.00,
    sizes: sizesMen,
    countInStock: 55,
  },
  {
    name: 'Striped Cotton Shirt',
    image: '/images/men-stripped-cotton-shirt.png',
    description: 'Cool cotton shirt featuring vertical stripes.',
    brand: 'UrbanGear',
    category: 'Men',
    price: 31.99,
    sizes: sizesMen,
    countInStock: 35,
  },
  {
    name: 'Tailored Fit Formal Shirt',
    image: '/images/men-tailored-fit-shirt.png',
    description: 'Professional tailored fit shirt for the office.',
    brand: 'UrbanGear',
    category: 'Men',
    price: 45.00,
    sizes: sizesMen,
    countInStock: 20,
  },

  // WOMEN (27)
  {
    name: 'Contrast Border Saree',
    image: '/images/women-checked-saree-with-contrast-border.png',
    description: 'Stylish checked saree with a striking contrast border.',
    brand: 'EthnicGrace',
    category: 'Women',
    price: 55.00,
    sizes: sizesWomen,
    countInStock: 15,
  },
  {
    name: 'Chest Print T-Shirt',
    image: '/images/women-chest-print-tshirt.png',
    description: 'Casual t-shirt with a trendy chest print design.',
    brand: 'ChicStyle',
    category: 'Women',
    price: 22.00,
    sizes: sizesWomen,
    countInStock: 40,
  },
  {
    name: 'Embroidered Lehanga Choli',
    image: '/images/women-embroidered-lehanga.png',
    description: 'Intricately embroidered lehanga set for weddings.',
    brand: 'EthnicGrace',
    category: 'Women',
    price: 150.00,
    sizes: sizesWomen,
    countInStock: 5,
  },
  {
    name: 'Embroidered Regular Fit Top',
    image: '/images/women-embroidered-regular-fit-top.png',
    description: 'Soft regular fit top with beautiful embroidery.',
    brand: 'ChicStyle',
    category: 'Women',
    price: 35.50,
    sizes: sizesWomen,
    countInStock: 25,
  },
  {
    name: 'Flared Wedding Lehanga',
    image: '/images/women-flared-lehanga.png',
    description: 'Grand flared lehanga for special festive occasions.',
    brand: 'EthnicGrace',
    category: 'Women',
    price: 210.00,
    sizes: sizesWomen,
    countInStock: 4,
  },
  {
    name: 'Floral Print Flare Dress',
    image: '/images/women-floral-print-and-flare-dress.png',
    description: 'Feminine flare dress with a vibrant floral print.',
    brand: 'ChicStyle',
    category: 'Women',
    price: 48.00,
    sizes: sizesWomen,
    countInStock: 20,
  },
  {
    name: 'Floral Print Summer Frock',
    image: '/images/women-floral-print-frock.png',
    description: 'Leisurely summer frock with a soft floral pattern.',
    brand: 'ChicStyle',
    category: 'Women',
    price: 32.99,
    sizes: sizesWomen,
    countInStock: 30,
  },
  {
    name: 'Floral Print Palazzo',
    image: '/images/women-floral-print-palazzo-with -pockets.png',
    description: 'Comfortable wide-leg palazzo pants with pockets.',
    brand: 'ChicStyle',
    category: 'Women',
    price: 28.50,
    sizes: sizesWomen,
    countInStock: 35,
  },
  {
    name: 'Designer Floral Saree',
    image: '/images/women-floral-print-saree.png',
    description: 'Lightweight designer saree with floral motifs.',
    brand: 'EthnicGrace',
    category: 'Women',
    price: 65.00,
    sizes: sizesWomen,
    countInStock: 15,
  },
  {
    name: 'Straight Cut Floral Kurta',
    image: '/images/women-floral-print-straight-kurta.png',
    description: 'Elegant straight cut kurta with floral prints.',
    brand: 'EthnicGrace',
    category: 'Women',
    price: 38.00,
    sizes: sizesWomen,
    countInStock: 25,
  },
  {
    name: 'V-Neck Straight Kurta',
    image: '/images/women-floral-print-V-neck-straight-kurta.png',
    description: 'Sophisticated V-neck kurta for everyday comfort.',
    brand: 'EthnicGrace',
    category: 'Women',
    price: 36.50,
    sizes: sizesWomen,
    countInStock: 30,
  },
  {
    name: 'Geometric Designer Handbag',
    image: '/images/women-geometric-handbag.png',
    description: 'Modern geometric pattern handbag for style icons.',
    brand: 'LuxeLeather',
    category: 'Women',
    price: 85.00,
    sizes: sizesAccessories,
    countInStock: 10,
  },
  {
    name: 'High Rise Bootcut Jeans',
    image: '/images/women-high-rise-bootcut-jeans.png',
    description: 'Flattering high rise jeans with a bootcut leg.',
    brand: 'DenimCo',
    category: 'Women',
    price: 52.00,
    sizes: sizesWomen,
    countInStock: 25,
  },
  {
    name: 'Artistic Kalamkari Saree',
    image: '/images/women-kalamkari-saree.png',
    description: 'Traditional Kalamkari hand-printed saree.',
    brand: 'EthnicGrace',
    category: 'Women',
    price: 89.99,
    sizes: sizesWomen,
    countInStock: 8,
  },
  {
    name: 'Traditional Pattu Silk Saree',
    image: '/images/women-pattu-silk-saree.png',
    description: 'Rich Pattu silk saree for grand traditional events.',
    brand: 'EthnicGrace',
    category: 'Women',
    price: 250.00,
    sizes: sizesWomen,
    countInStock: 5,
  },
  {
    name: 'Printed Cotton Saree',
    image: '/images/women-printed-cotton-saree.png',
    description: 'Comfortable printed cotton saree for daily wear.',
    brand: 'EthnicGrace',
    category: 'Women',
    price: 35.00,
    sizes: sizesWomen,
    countInStock: 40,
  },
  {
    name: 'Soft Printed Night Gown',
    image: '/images/women-printed-night-gown.png',
    description: 'Relaxing night gown with a soothing print.',
    brand: 'SweetDreams',
    category: 'Women',
    price: 29.99,
    sizes: sizesWomen,
    countInStock: 45,
  },
  {
    name: 'Comfortable Night Wear Set',
    image: '/images/women-printed-night-wear.png',
    description: 'Pack of night wear items for full comfort.',
    brand: 'SweetDreams',
    category: 'Women',
    price: 34.50,
    sizes: sizesWomen,
    countInStock: 50,
  },
  {
    name: 'Regular Fit Floral Top',
    image: '/images/women-regular-fit-floral-top.png',
    description: 'Vibrant regular fit top for casual outings.',
    brand: 'ChicStyle',
    category: 'Women',
    price: 26.00,
    sizes: sizesWomen,
    countInStock: 35,
  },
  {
    name: 'Basic Regular Fit T-Shirt',
    image: '/images/women-regular-fit-tshirt.png',
    description: 'Essential basic t-shirt in a clean regular fit.',
    brand: 'ChicStyle',
    category: 'Women',
    price: 18.00,
    sizes: sizesWomen,
    countInStock: 100,
  },
  {
    name: 'Trendy Ribbed Fit Top',
    image: '/images/women-ribbed-fit-top.png',
    description: 'Sleek ribbed pattern top for a modern look.',
    brand: 'ChicStyle',
    category: 'Women',
    price: 24.50,
    sizes: sizesWomen,
    countInStock: 30,
  },
  {
    name: 'Skinny Mid Rise Blue Jeans',
    image: '/images/women-skinny-mid-rise-fit-blue-jeans.png',
    description: 'Classic skinny fit jeans with a mid-rise waist.',
    brand: 'DenimCo',
    category: 'Women',
    price: 49.99,
    sizes: sizesWomen,
    countInStock: 40,
  },
  {
    name: 'Full Sleeve Slim Fit T-Shirt',
    image: '/images/women-slimfit-fullhands-tshirt.png',
    description: 'Soft full sleeve t-shirt with a snug slim fit.',
    brand: 'ChicStyle',
    category: 'Women',
    price: 29.00,
    sizes: sizesWomen,
    countInStock: 35,
  },
  {
    name: 'Straight Leg Black Jeans',
    image: '/images/women-straight-black-jeans.png',
    description: 'Essential straight cut jeans in versatile black.',
    brand: 'DenimCo',
    category: 'Women',
    price: 45.00,
    sizes: sizesWomen,
    countInStock: 30,
  },
  {
    name: 'Typographic Co-ord Set',
    image: '/images/women-typographic-co-ord-set.png',
    description: 'Fashionable co-ord set with typographic prints.',
    brand: 'UrbanGear',
    category: 'Women',
    price: 59.99,
    sizes: sizesWomen,
    countInStock: 15,
  },
  {
    name: 'V-Neck Straight Tunic',
    image: '/images/women-V-neck-straight-tunic.png',
    description: 'Elegant straight cut tunic with a classic V-neck.',
    brand: 'ChicStyle',
    category: 'Women',
    price: 42.00,
    sizes: sizesWomen,
    countInStock: 20,
  },
  {
    name: 'Woven Black Kurta',
    image: '/images/women-woven-black-kurtha.png',
    description: 'Stylish woven kurta in sophisticated black.',
    brand: 'EthnicGrace',
    category: 'Women',
    price: 55.00,
    sizes: sizesWomen,
    countInStock: 25,
  },
];

const seedData = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    await Product.deleteMany();
    await Product.insertMany(products);

    console.log('73 Products with sizes imported successfully!');
    process.exit();
  } catch (error) {
    console.error(`Error with data import: ${error.message}`);
    process.exit(1);
  }
};

seedData();
